### ISSUE TITLE
Change the default to 0.0.0.0?

### ISSUE THREAD

**Issue by asottile** [Yelp/ephemeral-port-reserve#2]
At least this is how paasta is using it: https://github.com/Yelp/paasta/commit/22627c31759d126e01c83bcba1cba3b4c9b36d71

**Comment by bukzor** [comment]
This won't give reliable results, and I tried to address it in the README, but probably should be more prominent:

> NOTE: By default, the port returned is specifically for localhost, aka 127.0.0.1. If you bind instead to 0.0.0.0, you may encounter a port conflict. If you need to bind to a non-localhost IP, you can pass it as the first argument.

The reason is that 0.0.0.0 is interpreted by the "port zero trick" as localhost aka 127.0.0.1, even though in all other context it means "all IPs on this machine". More specifically, when given 0.0.0.0, there's only one port, bound to 127.0.0.1, which will enter the necessary TIME_WAIT state.

**Comment by bukzor** [comment]
Instead of leaving this to documentation, let's just reject that IP (0.0.0.0) with an explanatory message like the one above, and give users the explicit option of localhost or an IP.

Agreeable?

**Comment by bukzor** [comment]
adding @chriskuehl

**Comment by chriskuehl** [comment]
Ugh, that's unfortunate. Sounds like rejecting (and major version bump) make sense.

There's no way to get a random port on 0.0.0.0 when binding to port 0?

**Comment by bukzor** [comment]
As far as I know, no. Could be wrong.

**Comment by bukzor** [comment]
Thinking about it a bit more, we could enhanced the script to connect on each IP when asked for a reservation on 0.0.0.0 (known as INADDR_ANY), but this would still result in a different port for each device, which seems pretty useless.

**Comment by asottile** [comment]
I'm pretty sure this works just fine, paasta has been using this without
problem?

**Comment by chriskuehl** [comment]
It seems to work?

```
ckuehl@raziel:~$ nc -l 0.0.0.0 -p 0 &
[1] 31920
ckuehl@raziel:~$ sudo netstat -tulpn | grep 31920
tcp        0      0 0.0.0.0:36091           0.0.0.0:*               LISTEN      31920/nc
```

**Comment by bukzor** [comment]
Uhhh... Maybe I've just been 100% wrong about this the whole time?
I could have sworn I spent hours debugging a port collision that should have been impossible and it boiled down to this.

Time for science.

**Comment by bukzor** [comment]
Yea, there's some difference between what netstat and e-p-r are doing:

```
$ python ephemeral_port_reserve.py 0.0.0.0 0
37929

$ sudo netstat -tulpna | grep 33463
tcp        0      0 127.0.0.1:33463         127.0.0.1:35422         TIME_WAIT   -        
```

**Comment by bukzor** [comment]
strace of netcat:

```
socket(AF_INET, SOCK_STREAM, IPPROTO_TCP) = 3
setsockopt(3, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
setsockopt(3, SOL_SOCKET, SO_REUSEPORT, [1], 4) = 0
bind(3, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
listen(3, 1)                            = 0
accept(3, 
```

strace of e.p.r.:

```
socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 3
setsockopt(3, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
bind(3, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
listen(3, 1)                            = 0
getsockname(3, {sa_family=AF_INET, sin_port=htons(37693), sin_addr=inet_addr("0.0.0.0")}, [16]) = 0
socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 4
connect(4, {sa_family=AF_INET, sin_port=htons(37693), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
close(4)                                = 0
close(3)                                = 0
```

If I add a bit of instrumentation, we see that there's three sockets involved. The port that ends up in time-wait is the local side of the "remote" socket (wrt the listening socket).

```
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    

tcp        0      0 0.0.0.0:40757           0.0.0.0:*               LISTEN      11179/python        

tcp        1      0 0.0.0.0:40757           0.0.0.0:*               LISTEN      11179/python        
tcp        0      0 127.0.0.1:40757         127.0.0.1:33438         ESTABLISHED -                   
tcp        0      0 127.0.0.1:33438         127.0.0.1:40757         ESTABLISHED 11179/python        

tcp        0      0 0.0.0.0:40757           0.0.0.0:*               LISTEN      11179/python        
tcp        0      0 127.0.0.1:40757         127.0.0.1:33438         ESTABLISHED 11179/python        
tcp        0      0 127.0.0.1:33438         127.0.0.1:40757         ESTABLISHED 11179/python        

tcp        0      0 127.0.0.1:33438         127.0.0.1:40757         TIME_WAIT   -
```

To get what you guys want, a 0.0.0.0 socket in time-wait state, we'd need to state-transition the original LISTENing socket to TIME_WAIT, and I don't know how. Have a gander at this state diagram:

![image](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Tcp_state_diagram_fixed.svg/796px-Tcp_state_diagram_fixed.svg.png)

Maybe we can use CLOSE_WAIT but I'm not sure how to induce that.
