### ISSUE TITLE
Use the errno module instead of hardcoded constant

### ISSUE THREAD

**Issue by ulope** [Yelp/ephemeral-port-reserve#6]
The check for address already in use uses a hardcoded constant:

https://github.com/Yelp/ephemeral-port-reserve/blob/d9b7fd5e7a89fa8ed362d1a78f498ad07caab652/ephemeral_port_reserve.py#L34

This breaks on non-linux platforms since the error numbers aren't standardised.
The portable way to write this is to  use `errno.EADDRINUSE`.

**Comment by asottile** [comment]
:+1:  -- submit a PR?

**Comment by ulope** [comment]
Sure, I should have some time tomorrow.
